// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: wkts.proto

package test

import (
	fmt "fmt"
	_ "github.com/TheThingsIndustries/protoc-gen-go-json/annotations"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MessageWithMarshaler struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageWithMarshaler) Reset()         { *m = MessageWithMarshaler{} }
func (m *MessageWithMarshaler) String() string { return proto.CompactTextString(m) }
func (*MessageWithMarshaler) ProtoMessage()    {}
func (*MessageWithMarshaler) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f76f3479ade79d3, []int{0}
}
func (m *MessageWithMarshaler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithMarshaler.Unmarshal(m, b)
}
func (m *MessageWithMarshaler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithMarshaler.Marshal(b, m, deterministic)
}
func (m *MessageWithMarshaler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithMarshaler.Merge(m, src)
}
func (m *MessageWithMarshaler) XXX_Size() int {
	return xxx_messageInfo_MessageWithMarshaler.Size(m)
}
func (m *MessageWithMarshaler) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithMarshaler.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithMarshaler proto.InternalMessageInfo

func (m *MessageWithMarshaler) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MessageWithoutMarshaler struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageWithoutMarshaler) Reset()         { *m = MessageWithoutMarshaler{} }
func (m *MessageWithoutMarshaler) String() string { return proto.CompactTextString(m) }
func (*MessageWithoutMarshaler) ProtoMessage()    {}
func (*MessageWithoutMarshaler) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f76f3479ade79d3, []int{1}
}
func (m *MessageWithoutMarshaler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithoutMarshaler.Unmarshal(m, b)
}
func (m *MessageWithoutMarshaler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithoutMarshaler.Marshal(b, m, deterministic)
}
func (m *MessageWithoutMarshaler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithoutMarshaler.Merge(m, src)
}
func (m *MessageWithoutMarshaler) XXX_Size() int {
	return xxx_messageInfo_MessageWithoutMarshaler.Size(m)
}
func (m *MessageWithoutMarshaler) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithoutMarshaler.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithoutMarshaler proto.InternalMessageInfo

func (m *MessageWithoutMarshaler) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MessageWithWKTs struct {
	DoubleValue          *types.DoubleValue   `protobuf:"bytes,1,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	DoubleValues         []*types.DoubleValue `protobuf:"bytes,2,rep,name=double_values,json=doubleValues,proto3" json:"double_values,omitempty"`
	FloatValue           *types.FloatValue    `protobuf:"bytes,3,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	FloatValues          []*types.FloatValue  `protobuf:"bytes,4,rep,name=float_values,json=floatValues,proto3" json:"float_values,omitempty"`
	Int32Value           *types.Int32Value    `protobuf:"bytes,5,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Int32Values          []*types.Int32Value  `protobuf:"bytes,6,rep,name=int32_values,json=int32Values,proto3" json:"int32_values,omitempty"`
	Int64Value           *types.Int64Value    `protobuf:"bytes,7,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Int64Values          []*types.Int64Value  `protobuf:"bytes,8,rep,name=int64_values,json=int64Values,proto3" json:"int64_values,omitempty"`
	Uint32Value          *types.UInt32Value   `protobuf:"bytes,9,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	Uint32Values         []*types.UInt32Value `protobuf:"bytes,10,rep,name=uint32_values,json=uint32Values,proto3" json:"uint32_values,omitempty"`
	Uint64Value          *types.UInt64Value   `protobuf:"bytes,11,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	Uint64Values         []*types.UInt64Value `protobuf:"bytes,12,rep,name=uint64_values,json=uint64Values,proto3" json:"uint64_values,omitempty"`
	BoolValue            *types.BoolValue     `protobuf:"bytes,13,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	BoolValues           []*types.BoolValue   `protobuf:"bytes,14,rep,name=bool_values,json=boolValues,proto3" json:"bool_values,omitempty"`
	StringValue          *types.StringValue   `protobuf:"bytes,15,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	StringValues         []*types.StringValue `protobuf:"bytes,16,rep,name=string_values,json=stringValues,proto3" json:"string_values,omitempty"`
	BytesValue           *types.BytesValue    `protobuf:"bytes,17,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	BytesValues          []*types.BytesValue  `protobuf:"bytes,18,rep,name=bytes_values,json=bytesValues,proto3" json:"bytes_values,omitempty"`
	EmptyValue           *types.Empty         `protobuf:"bytes,19,opt,name=empty_value,json=emptyValue,proto3" json:"empty_value,omitempty"`
	EmptyValues          []*types.Empty       `protobuf:"bytes,20,rep,name=empty_values,json=emptyValues,proto3" json:"empty_values,omitempty"`
	TimestampValue       *types.Timestamp     `protobuf:"bytes,21,opt,name=timestamp_value,json=timestampValue,proto3" json:"timestamp_value,omitempty"`
	TimestampValues      []*types.Timestamp   `protobuf:"bytes,22,rep,name=timestamp_values,json=timestampValues,proto3" json:"timestamp_values,omitempty"`
	DurationValue        *types.Duration      `protobuf:"bytes,23,opt,name=duration_value,json=durationValue,proto3" json:"duration_value,omitempty"`
	DurationValues       []*types.Duration    `protobuf:"bytes,24,rep,name=duration_values,json=durationValues,proto3" json:"duration_values,omitempty"`
	FieldMaskValue       *types.FieldMask     `protobuf:"bytes,25,opt,name=field_mask_value,json=fieldMaskValue,proto3" json:"field_mask_value,omitempty"`
	FieldMaskValues      []*types.FieldMask   `protobuf:"bytes,26,rep,name=field_mask_values,json=fieldMaskValues,proto3" json:"field_mask_values,omitempty"`
	ValueValue           *types.Value         `protobuf:"bytes,27,opt,name=value_value,json=valueValue,proto3" json:"value_value,omitempty"`
	ValueValues          []*types.Value       `protobuf:"bytes,28,rep,name=value_values,json=valueValues,proto3" json:"value_values,omitempty"`
	ListValueValue       *types.ListValue     `protobuf:"bytes,29,opt,name=list_value_value,json=listValueValue,proto3" json:"list_value_value,omitempty"`
	ListValueValues      []*types.ListValue   `protobuf:"bytes,30,rep,name=list_value_values,json=listValueValues,proto3" json:"list_value_values,omitempty"`
	StructValue          *types.Struct        `protobuf:"bytes,31,opt,name=struct_value,json=structValue,proto3" json:"struct_value,omitempty"`
	StructValues         []*types.Struct      `protobuf:"bytes,32,rep,name=struct_values,json=structValues,proto3" json:"struct_values,omitempty"`
	AnyValue             *types.Any           `protobuf:"bytes,33,opt,name=any_value,json=anyValue,proto3" json:"any_value,omitempty"`
	AnyValues            []*types.Any         `protobuf:"bytes,34,rep,name=any_values,json=anyValues,proto3" json:"any_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MessageWithWKTs) Reset()         { *m = MessageWithWKTs{} }
func (m *MessageWithWKTs) String() string { return proto.CompactTextString(m) }
func (*MessageWithWKTs) ProtoMessage()    {}
func (*MessageWithWKTs) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f76f3479ade79d3, []int{2}
}
func (m *MessageWithWKTs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithWKTs.Unmarshal(m, b)
}
func (m *MessageWithWKTs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithWKTs.Marshal(b, m, deterministic)
}
func (m *MessageWithWKTs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithWKTs.Merge(m, src)
}
func (m *MessageWithWKTs) XXX_Size() int {
	return xxx_messageInfo_MessageWithWKTs.Size(m)
}
func (m *MessageWithWKTs) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithWKTs.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithWKTs proto.InternalMessageInfo

func (m *MessageWithWKTs) GetDoubleValue() *types.DoubleValue {
	if m != nil {
		return m.DoubleValue
	}
	return nil
}

func (m *MessageWithWKTs) GetDoubleValues() []*types.DoubleValue {
	if m != nil {
		return m.DoubleValues
	}
	return nil
}

func (m *MessageWithWKTs) GetFloatValue() *types.FloatValue {
	if m != nil {
		return m.FloatValue
	}
	return nil
}

func (m *MessageWithWKTs) GetFloatValues() []*types.FloatValue {
	if m != nil {
		return m.FloatValues
	}
	return nil
}

func (m *MessageWithWKTs) GetInt32Value() *types.Int32Value {
	if m != nil {
		return m.Int32Value
	}
	return nil
}

func (m *MessageWithWKTs) GetInt32Values() []*types.Int32Value {
	if m != nil {
		return m.Int32Values
	}
	return nil
}

func (m *MessageWithWKTs) GetInt64Value() *types.Int64Value {
	if m != nil {
		return m.Int64Value
	}
	return nil
}

func (m *MessageWithWKTs) GetInt64Values() []*types.Int64Value {
	if m != nil {
		return m.Int64Values
	}
	return nil
}

func (m *MessageWithWKTs) GetUint32Value() *types.UInt32Value {
	if m != nil {
		return m.Uint32Value
	}
	return nil
}

func (m *MessageWithWKTs) GetUint32Values() []*types.UInt32Value {
	if m != nil {
		return m.Uint32Values
	}
	return nil
}

func (m *MessageWithWKTs) GetUint64Value() *types.UInt64Value {
	if m != nil {
		return m.Uint64Value
	}
	return nil
}

func (m *MessageWithWKTs) GetUint64Values() []*types.UInt64Value {
	if m != nil {
		return m.Uint64Values
	}
	return nil
}

func (m *MessageWithWKTs) GetBoolValue() *types.BoolValue {
	if m != nil {
		return m.BoolValue
	}
	return nil
}

func (m *MessageWithWKTs) GetBoolValues() []*types.BoolValue {
	if m != nil {
		return m.BoolValues
	}
	return nil
}

func (m *MessageWithWKTs) GetStringValue() *types.StringValue {
	if m != nil {
		return m.StringValue
	}
	return nil
}

func (m *MessageWithWKTs) GetStringValues() []*types.StringValue {
	if m != nil {
		return m.StringValues
	}
	return nil
}

func (m *MessageWithWKTs) GetBytesValue() *types.BytesValue {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

func (m *MessageWithWKTs) GetBytesValues() []*types.BytesValue {
	if m != nil {
		return m.BytesValues
	}
	return nil
}

func (m *MessageWithWKTs) GetEmptyValue() *types.Empty {
	if m != nil {
		return m.EmptyValue
	}
	return nil
}

func (m *MessageWithWKTs) GetEmptyValues() []*types.Empty {
	if m != nil {
		return m.EmptyValues
	}
	return nil
}

func (m *MessageWithWKTs) GetTimestampValue() *types.Timestamp {
	if m != nil {
		return m.TimestampValue
	}
	return nil
}

func (m *MessageWithWKTs) GetTimestampValues() []*types.Timestamp {
	if m != nil {
		return m.TimestampValues
	}
	return nil
}

func (m *MessageWithWKTs) GetDurationValue() *types.Duration {
	if m != nil {
		return m.DurationValue
	}
	return nil
}

func (m *MessageWithWKTs) GetDurationValues() []*types.Duration {
	if m != nil {
		return m.DurationValues
	}
	return nil
}

func (m *MessageWithWKTs) GetFieldMaskValue() *types.FieldMask {
	if m != nil {
		return m.FieldMaskValue
	}
	return nil
}

func (m *MessageWithWKTs) GetFieldMaskValues() []*types.FieldMask {
	if m != nil {
		return m.FieldMaskValues
	}
	return nil
}

func (m *MessageWithWKTs) GetValueValue() *types.Value {
	if m != nil {
		return m.ValueValue
	}
	return nil
}

func (m *MessageWithWKTs) GetValueValues() []*types.Value {
	if m != nil {
		return m.ValueValues
	}
	return nil
}

func (m *MessageWithWKTs) GetListValueValue() *types.ListValue {
	if m != nil {
		return m.ListValueValue
	}
	return nil
}

func (m *MessageWithWKTs) GetListValueValues() []*types.ListValue {
	if m != nil {
		return m.ListValueValues
	}
	return nil
}

func (m *MessageWithWKTs) GetStructValue() *types.Struct {
	if m != nil {
		return m.StructValue
	}
	return nil
}

func (m *MessageWithWKTs) GetStructValues() []*types.Struct {
	if m != nil {
		return m.StructValues
	}
	return nil
}

func (m *MessageWithWKTs) GetAnyValue() *types.Any {
	if m != nil {
		return m.AnyValue
	}
	return nil
}

func (m *MessageWithWKTs) GetAnyValues() []*types.Any {
	if m != nil {
		return m.AnyValues
	}
	return nil
}

type MessageWithOneofWKTs struct {
	// Types that are valid to be assigned to Value:
	//	*MessageWithOneofWKTs_DoubleValue
	//	*MessageWithOneofWKTs_FloatValue
	//	*MessageWithOneofWKTs_Int32Value
	//	*MessageWithOneofWKTs_Int64Value
	//	*MessageWithOneofWKTs_Uint32Value
	//	*MessageWithOneofWKTs_Uint64Value
	//	*MessageWithOneofWKTs_BoolValue
	//	*MessageWithOneofWKTs_StringValue
	//	*MessageWithOneofWKTs_BytesValue
	//	*MessageWithOneofWKTs_EmptyValue
	//	*MessageWithOneofWKTs_TimestampValue
	//	*MessageWithOneofWKTs_DurationValue
	//	*MessageWithOneofWKTs_FieldMaskValue
	//	*MessageWithOneofWKTs_ValueValue
	//	*MessageWithOneofWKTs_ListValueValue
	//	*MessageWithOneofWKTs_StructValue
	//	*MessageWithOneofWKTs_AnyValue
	Value                isMessageWithOneofWKTs_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *MessageWithOneofWKTs) Reset()         { *m = MessageWithOneofWKTs{} }
func (m *MessageWithOneofWKTs) String() string { return proto.CompactTextString(m) }
func (*MessageWithOneofWKTs) ProtoMessage()    {}
func (*MessageWithOneofWKTs) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f76f3479ade79d3, []int{3}
}
func (m *MessageWithOneofWKTs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithOneofWKTs.Unmarshal(m, b)
}
func (m *MessageWithOneofWKTs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithOneofWKTs.Marshal(b, m, deterministic)
}
func (m *MessageWithOneofWKTs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithOneofWKTs.Merge(m, src)
}
func (m *MessageWithOneofWKTs) XXX_Size() int {
	return xxx_messageInfo_MessageWithOneofWKTs.Size(m)
}
func (m *MessageWithOneofWKTs) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithOneofWKTs.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithOneofWKTs proto.InternalMessageInfo

type isMessageWithOneofWKTs_Value interface {
	isMessageWithOneofWKTs_Value()
}

type MessageWithOneofWKTs_DoubleValue struct {
	DoubleValue *types.DoubleValue `protobuf:"bytes,1,opt,name=double_value,json=doubleValue,proto3,oneof" json:"double_value,omitempty"`
}
type MessageWithOneofWKTs_FloatValue struct {
	FloatValue *types.FloatValue `protobuf:"bytes,2,opt,name=float_value,json=floatValue,proto3,oneof" json:"float_value,omitempty"`
}
type MessageWithOneofWKTs_Int32Value struct {
	Int32Value *types.Int32Value `protobuf:"bytes,3,opt,name=int32_value,json=int32Value,proto3,oneof" json:"int32_value,omitempty"`
}
type MessageWithOneofWKTs_Int64Value struct {
	Int64Value *types.Int64Value `protobuf:"bytes,4,opt,name=int64_value,json=int64Value,proto3,oneof" json:"int64_value,omitempty"`
}
type MessageWithOneofWKTs_Uint32Value struct {
	Uint32Value *types.UInt32Value `protobuf:"bytes,5,opt,name=uint32_value,json=uint32Value,proto3,oneof" json:"uint32_value,omitempty"`
}
type MessageWithOneofWKTs_Uint64Value struct {
	Uint64Value *types.UInt64Value `protobuf:"bytes,6,opt,name=uint64_value,json=uint64Value,proto3,oneof" json:"uint64_value,omitempty"`
}
type MessageWithOneofWKTs_BoolValue struct {
	BoolValue *types.BoolValue `protobuf:"bytes,7,opt,name=bool_value,json=boolValue,proto3,oneof" json:"bool_value,omitempty"`
}
type MessageWithOneofWKTs_StringValue struct {
	StringValue *types.StringValue `protobuf:"bytes,8,opt,name=string_value,json=stringValue,proto3,oneof" json:"string_value,omitempty"`
}
type MessageWithOneofWKTs_BytesValue struct {
	BytesValue *types.BytesValue `protobuf:"bytes,9,opt,name=bytes_value,json=bytesValue,proto3,oneof" json:"bytes_value,omitempty"`
}
type MessageWithOneofWKTs_EmptyValue struct {
	EmptyValue *types.Empty `protobuf:"bytes,10,opt,name=empty_value,json=emptyValue,proto3,oneof" json:"empty_value,omitempty"`
}
type MessageWithOneofWKTs_TimestampValue struct {
	TimestampValue *types.Timestamp `protobuf:"bytes,11,opt,name=timestamp_value,json=timestampValue,proto3,oneof" json:"timestamp_value,omitempty"`
}
type MessageWithOneofWKTs_DurationValue struct {
	DurationValue *types.Duration `protobuf:"bytes,12,opt,name=duration_value,json=durationValue,proto3,oneof" json:"duration_value,omitempty"`
}
type MessageWithOneofWKTs_FieldMaskValue struct {
	FieldMaskValue *types.FieldMask `protobuf:"bytes,13,opt,name=field_mask_value,json=fieldMaskValue,proto3,oneof" json:"field_mask_value,omitempty"`
}
type MessageWithOneofWKTs_ValueValue struct {
	ValueValue *types.Value `protobuf:"bytes,14,opt,name=value_value,json=valueValue,proto3,oneof" json:"value_value,omitempty"`
}
type MessageWithOneofWKTs_ListValueValue struct {
	ListValueValue *types.ListValue `protobuf:"bytes,15,opt,name=list_value_value,json=listValueValue,proto3,oneof" json:"list_value_value,omitempty"`
}
type MessageWithOneofWKTs_StructValue struct {
	StructValue *types.Struct `protobuf:"bytes,16,opt,name=struct_value,json=structValue,proto3,oneof" json:"struct_value,omitempty"`
}
type MessageWithOneofWKTs_AnyValue struct {
	AnyValue *types.Any `protobuf:"bytes,17,opt,name=any_value,json=anyValue,proto3,oneof" json:"any_value,omitempty"`
}

func (*MessageWithOneofWKTs_DoubleValue) isMessageWithOneofWKTs_Value()    {}
func (*MessageWithOneofWKTs_FloatValue) isMessageWithOneofWKTs_Value()     {}
func (*MessageWithOneofWKTs_Int32Value) isMessageWithOneofWKTs_Value()     {}
func (*MessageWithOneofWKTs_Int64Value) isMessageWithOneofWKTs_Value()     {}
func (*MessageWithOneofWKTs_Uint32Value) isMessageWithOneofWKTs_Value()    {}
func (*MessageWithOneofWKTs_Uint64Value) isMessageWithOneofWKTs_Value()    {}
func (*MessageWithOneofWKTs_BoolValue) isMessageWithOneofWKTs_Value()      {}
func (*MessageWithOneofWKTs_StringValue) isMessageWithOneofWKTs_Value()    {}
func (*MessageWithOneofWKTs_BytesValue) isMessageWithOneofWKTs_Value()     {}
func (*MessageWithOneofWKTs_EmptyValue) isMessageWithOneofWKTs_Value()     {}
func (*MessageWithOneofWKTs_TimestampValue) isMessageWithOneofWKTs_Value() {}
func (*MessageWithOneofWKTs_DurationValue) isMessageWithOneofWKTs_Value()  {}
func (*MessageWithOneofWKTs_FieldMaskValue) isMessageWithOneofWKTs_Value() {}
func (*MessageWithOneofWKTs_ValueValue) isMessageWithOneofWKTs_Value()     {}
func (*MessageWithOneofWKTs_ListValueValue) isMessageWithOneofWKTs_Value() {}
func (*MessageWithOneofWKTs_StructValue) isMessageWithOneofWKTs_Value()    {}
func (*MessageWithOneofWKTs_AnyValue) isMessageWithOneofWKTs_Value()       {}

func (m *MessageWithOneofWKTs) GetValue() isMessageWithOneofWKTs_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetDoubleValue() *types.DoubleValue {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_DoubleValue); ok {
		return x.DoubleValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetFloatValue() *types.FloatValue {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_FloatValue); ok {
		return x.FloatValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetInt32Value() *types.Int32Value {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_Int32Value); ok {
		return x.Int32Value
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetInt64Value() *types.Int64Value {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_Int64Value); ok {
		return x.Int64Value
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetUint32Value() *types.UInt32Value {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_Uint32Value); ok {
		return x.Uint32Value
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetUint64Value() *types.UInt64Value {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_Uint64Value); ok {
		return x.Uint64Value
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetBoolValue() *types.BoolValue {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_BoolValue); ok {
		return x.BoolValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetStringValue() *types.StringValue {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_StringValue); ok {
		return x.StringValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetBytesValue() *types.BytesValue {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetEmptyValue() *types.Empty {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_EmptyValue); ok {
		return x.EmptyValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetTimestampValue() *types.Timestamp {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_TimestampValue); ok {
		return x.TimestampValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetDurationValue() *types.Duration {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_DurationValue); ok {
		return x.DurationValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetFieldMaskValue() *types.FieldMask {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_FieldMaskValue); ok {
		return x.FieldMaskValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetValueValue() *types.Value {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_ValueValue); ok {
		return x.ValueValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetListValueValue() *types.ListValue {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_ListValueValue); ok {
		return x.ListValueValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetStructValue() *types.Struct {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_StructValue); ok {
		return x.StructValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetAnyValue() *types.Any {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_AnyValue); ok {
		return x.AnyValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MessageWithOneofWKTs) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MessageWithOneofWKTs_DoubleValue)(nil),
		(*MessageWithOneofWKTs_FloatValue)(nil),
		(*MessageWithOneofWKTs_Int32Value)(nil),
		(*MessageWithOneofWKTs_Int64Value)(nil),
		(*MessageWithOneofWKTs_Uint32Value)(nil),
		(*MessageWithOneofWKTs_Uint64Value)(nil),
		(*MessageWithOneofWKTs_BoolValue)(nil),
		(*MessageWithOneofWKTs_StringValue)(nil),
		(*MessageWithOneofWKTs_BytesValue)(nil),
		(*MessageWithOneofWKTs_EmptyValue)(nil),
		(*MessageWithOneofWKTs_TimestampValue)(nil),
		(*MessageWithOneofWKTs_DurationValue)(nil),
		(*MessageWithOneofWKTs_FieldMaskValue)(nil),
		(*MessageWithOneofWKTs_ValueValue)(nil),
		(*MessageWithOneofWKTs_ListValueValue)(nil),
		(*MessageWithOneofWKTs_StructValue)(nil),
		(*MessageWithOneofWKTs_AnyValue)(nil),
	}
}

type MessageWithWKTMaps struct {
	StringDoubleMap      map[string]*types.DoubleValue `protobuf:"bytes,1,rep,name=string_double_map,json=stringDoubleMap,proto3" json:"string_double_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringFloatMap       map[string]*types.FloatValue  `protobuf:"bytes,2,rep,name=string_float_map,json=stringFloatMap,proto3" json:"string_float_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringInt32Map       map[string]*types.Int32Value  `protobuf:"bytes,3,rep,name=string_int32_map,json=stringInt32Map,proto3" json:"string_int32_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringInt64Map       map[string]*types.Int64Value  `protobuf:"bytes,4,rep,name=string_int64_map,json=stringInt64Map,proto3" json:"string_int64_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringUint32Map      map[string]*types.UInt32Value `protobuf:"bytes,5,rep,name=string_uint32_map,json=stringUint32Map,proto3" json:"string_uint32_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringUint64Map      map[string]*types.UInt64Value `protobuf:"bytes,6,rep,name=string_uint64_map,json=stringUint64Map,proto3" json:"string_uint64_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringBoolMap        map[string]*types.BoolValue   `protobuf:"bytes,7,rep,name=string_bool_map,json=stringBoolMap,proto3" json:"string_bool_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringStringMap      map[string]*types.StringValue `protobuf:"bytes,8,rep,name=string_string_map,json=stringStringMap,proto3" json:"string_string_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringBytesMap       map[string]*types.BytesValue  `protobuf:"bytes,9,rep,name=string_bytes_map,json=stringBytesMap,proto3" json:"string_bytes_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringEmptyMap       map[string]*types.Empty       `protobuf:"bytes,10,rep,name=string_empty_map,json=stringEmptyMap,proto3" json:"string_empty_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringTimestampMap   map[string]*types.Timestamp   `protobuf:"bytes,11,rep,name=string_timestamp_map,json=stringTimestampMap,proto3" json:"string_timestamp_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringDurationMap    map[string]*types.Duration    `protobuf:"bytes,12,rep,name=string_duration_map,json=stringDurationMap,proto3" json:"string_duration_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringFieldMaskMap   map[string]*types.FieldMask   `protobuf:"bytes,13,rep,name=string_field_mask_map,json=stringFieldMaskMap,proto3" json:"string_field_mask_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringValueMap       map[string]*types.Value       `protobuf:"bytes,14,rep,name=string_value_map,json=stringValueMap,proto3" json:"string_value_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringListValueMap   map[string]*types.ListValue   `protobuf:"bytes,15,rep,name=string_list_value_map,json=stringListValueMap,proto3" json:"string_list_value_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringStructMap      map[string]*types.Struct      `protobuf:"bytes,16,rep,name=string_struct_map,json=stringStructMap,proto3" json:"string_struct_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringAnyMap         map[string]*types.Any         `protobuf:"bytes,17,rep,name=string_any_map,json=stringAnyMap,proto3" json:"string_any_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *MessageWithWKTMaps) Reset()         { *m = MessageWithWKTMaps{} }
func (m *MessageWithWKTMaps) String() string { return proto.CompactTextString(m) }
func (*MessageWithWKTMaps) ProtoMessage()    {}
func (*MessageWithWKTMaps) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f76f3479ade79d3, []int{4}
}
func (m *MessageWithWKTMaps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithWKTMaps.Unmarshal(m, b)
}
func (m *MessageWithWKTMaps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithWKTMaps.Marshal(b, m, deterministic)
}
func (m *MessageWithWKTMaps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithWKTMaps.Merge(m, src)
}
func (m *MessageWithWKTMaps) XXX_Size() int {
	return xxx_messageInfo_MessageWithWKTMaps.Size(m)
}
func (m *MessageWithWKTMaps) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithWKTMaps.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithWKTMaps proto.InternalMessageInfo

func (m *MessageWithWKTMaps) GetStringDoubleMap() map[string]*types.DoubleValue {
	if m != nil {
		return m.StringDoubleMap
	}
	return nil
}

func (m *MessageWithWKTMaps) GetStringFloatMap() map[string]*types.FloatValue {
	if m != nil {
		return m.StringFloatMap
	}
	return nil
}

func (m *MessageWithWKTMaps) GetStringInt32Map() map[string]*types.Int32Value {
	if m != nil {
		return m.StringInt32Map
	}
	return nil
}

func (m *MessageWithWKTMaps) GetStringInt64Map() map[string]*types.Int64Value {
	if m != nil {
		return m.StringInt64Map
	}
	return nil
}

func (m *MessageWithWKTMaps) GetStringUint32Map() map[string]*types.UInt32Value {
	if m != nil {
		return m.StringUint32Map
	}
	return nil
}

func (m *MessageWithWKTMaps) GetStringUint64Map() map[string]*types.UInt64Value {
	if m != nil {
		return m.StringUint64Map
	}
	return nil
}

func (m *MessageWithWKTMaps) GetStringBoolMap() map[string]*types.BoolValue {
	if m != nil {
		return m.StringBoolMap
	}
	return nil
}

func (m *MessageWithWKTMaps) GetStringStringMap() map[string]*types.StringValue {
	if m != nil {
		return m.StringStringMap
	}
	return nil
}

func (m *MessageWithWKTMaps) GetStringBytesMap() map[string]*types.BytesValue {
	if m != nil {
		return m.StringBytesMap
	}
	return nil
}

func (m *MessageWithWKTMaps) GetStringEmptyMap() map[string]*types.Empty {
	if m != nil {
		return m.StringEmptyMap
	}
	return nil
}

func (m *MessageWithWKTMaps) GetStringTimestampMap() map[string]*types.Timestamp {
	if m != nil {
		return m.StringTimestampMap
	}
	return nil
}

func (m *MessageWithWKTMaps) GetStringDurationMap() map[string]*types.Duration {
	if m != nil {
		return m.StringDurationMap
	}
	return nil
}

func (m *MessageWithWKTMaps) GetStringFieldMaskMap() map[string]*types.FieldMask {
	if m != nil {
		return m.StringFieldMaskMap
	}
	return nil
}

func (m *MessageWithWKTMaps) GetStringValueMap() map[string]*types.Value {
	if m != nil {
		return m.StringValueMap
	}
	return nil
}

func (m *MessageWithWKTMaps) GetStringListValueMap() map[string]*types.ListValue {
	if m != nil {
		return m.StringListValueMap
	}
	return nil
}

func (m *MessageWithWKTMaps) GetStringStructMap() map[string]*types.Struct {
	if m != nil {
		return m.StringStructMap
	}
	return nil
}

func (m *MessageWithWKTMaps) GetStringAnyMap() map[string]*types.Any {
	if m != nil {
		return m.StringAnyMap
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageWithMarshaler)(nil), "thethings.json.test.MessageWithMarshaler")
	proto.RegisterType((*MessageWithoutMarshaler)(nil), "thethings.json.test.MessageWithoutMarshaler")
	proto.RegisterType((*MessageWithWKTs)(nil), "thethings.json.test.MessageWithWKTs")
	proto.RegisterType((*MessageWithOneofWKTs)(nil), "thethings.json.test.MessageWithOneofWKTs")
	proto.RegisterType((*MessageWithWKTMaps)(nil), "thethings.json.test.MessageWithWKTMaps")
	proto.RegisterMapType((map[string]*types.Any)(nil), "thethings.json.test.MessageWithWKTMaps.StringAnyMapEntry")
	proto.RegisterMapType((map[string]*types.BoolValue)(nil), "thethings.json.test.MessageWithWKTMaps.StringBoolMapEntry")
	proto.RegisterMapType((map[string]*types.BytesValue)(nil), "thethings.json.test.MessageWithWKTMaps.StringBytesMapEntry")
	proto.RegisterMapType((map[string]*types.DoubleValue)(nil), "thethings.json.test.MessageWithWKTMaps.StringDoubleMapEntry")
	proto.RegisterMapType((map[string]*types.Duration)(nil), "thethings.json.test.MessageWithWKTMaps.StringDurationMapEntry")
	proto.RegisterMapType((map[string]*types.Empty)(nil), "thethings.json.test.MessageWithWKTMaps.StringEmptyMapEntry")
	proto.RegisterMapType((map[string]*types.FieldMask)(nil), "thethings.json.test.MessageWithWKTMaps.StringFieldMaskMapEntry")
	proto.RegisterMapType((map[string]*types.FloatValue)(nil), "thethings.json.test.MessageWithWKTMaps.StringFloatMapEntry")
	proto.RegisterMapType((map[string]*types.Int32Value)(nil), "thethings.json.test.MessageWithWKTMaps.StringInt32MapEntry")
	proto.RegisterMapType((map[string]*types.Int64Value)(nil), "thethings.json.test.MessageWithWKTMaps.StringInt64MapEntry")
	proto.RegisterMapType((map[string]*types.ListValue)(nil), "thethings.json.test.MessageWithWKTMaps.StringListValueMapEntry")
	proto.RegisterMapType((map[string]*types.StringValue)(nil), "thethings.json.test.MessageWithWKTMaps.StringStringMapEntry")
	proto.RegisterMapType((map[string]*types.Struct)(nil), "thethings.json.test.MessageWithWKTMaps.StringStructMapEntry")
	proto.RegisterMapType((map[string]*types.Timestamp)(nil), "thethings.json.test.MessageWithWKTMaps.StringTimestampMapEntry")
	proto.RegisterMapType((map[string]*types.UInt32Value)(nil), "thethings.json.test.MessageWithWKTMaps.StringUint32MapEntry")
	proto.RegisterMapType((map[string]*types.UInt64Value)(nil), "thethings.json.test.MessageWithWKTMaps.StringUint64MapEntry")
	proto.RegisterMapType((map[string]*types.Value)(nil), "thethings.json.test.MessageWithWKTMaps.StringValueMapEntry")
}

func init() { proto.RegisterFile("wkts.proto", fileDescriptor_4f76f3479ade79d3) }

var fileDescriptor_4f76f3479ade79d3 = []byte{
	// 1630 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x59, 0xed, 0x52, 0xdb, 0x46,
	0x17, 0x36, 0xe1, 0xcb, 0x5e, 0x19, 0x7f, 0x08, 0x12, 0x84, 0x93, 0x37, 0xe1, 0xe5, 0xd7, 0x3b,
	0xef, 0x14, 0x93, 0x04, 0x86, 0x16, 0x42, 0x49, 0xa0, 0x81, 0x21, 0xd3, 0x32, 0x9d, 0x71, 0xa1,
	0x99, 0x7e, 0x4c, 0xa9, 0x6c, 0x84, 0xed, 0x62, 0x4b, 0xae, 0x57, 0x4a, 0x86, 0x4b, 0xe8, 0xad,
	0xf4, 0xd2, 0x3a, 0xbd, 0x82, 0xfe, 0xea, 0xec, 0xea, 0xac, 0xf6, 0xac, 0xa4, 0x95, 0x82, 0xfe,
	0x24, 0xf2, 0xee, 0x3e, 0xe7, 0x39, 0x67, 0x77, 0xf5, 0x3c, 0xab, 0x85, 0x90, 0x8f, 0xb7, 0x3e,
	0x6d, 0x4f, 0xa6, 0x9e, 0xef, 0x99, 0xcb, 0xfe, 0xc0, 0xf1, 0x07, 0x43, 0xb7, 0x4f, 0xdb, 0xbf,
	0x51, 0xcf, 0x6d, 0xfb, 0x0e, 0xf5, 0x5b, 0x4d, 0xdb, 0x75, 0x3d, 0xdf, 0xf6, 0x87, 0x9e, 0x0b,
	0xe3, 0x5a, 0x6b, 0x7d, 0xcf, 0xeb, 0x8f, 0x9c, 0x2d, 0xfe, 0xab, 0x1b, 0xdc, 0x6c, 0xd9, 0xee,
	0x1d, 0x74, 0x3d, 0x8d, 0x77, 0x5d, 0x07, 0x53, 0x8e, 0x85, 0xfe, 0xc7, 0xf1, 0x7e, 0x67, 0x3c,
	0xf1, 0x05, 0x78, 0x3d, 0xde, 0x79, 0x33, 0x74, 0x46, 0xd7, 0x57, 0x63, 0x9b, 0xde, 0xc2, 0x88,
	0x27, 0xf1, 0x11, 0xd4, 0x9f, 0x06, 0x3d, 0x1f, 0x7a, 0x9f, 0xc5, 0x7b, 0xfd, 0xe1, 0xd8, 0xa1,
	0xbe, 0x3d, 0x9e, 0xe8, 0xb2, 0xfb, 0x38, 0xb5, 0x27, 0x13, 0x67, 0x0a, 0x85, 0x6d, 0x3c, 0x27,
	0x2b, 0xe7, 0x0e, 0xa5, 0x76, 0xdf, 0x79, 0x3f, 0xf4, 0x07, 0xe7, 0xf6, 0x94, 0x0e, 0xec, 0x91,
	0x33, 0x35, 0x2d, 0xb2, 0x38, 0x0e, 0xdb, 0xad, 0x99, 0xf5, 0x99, 0xff, 0x55, 0x3a, 0xe2, 0xe7,
	0xc6, 0x97, 0x64, 0x15, 0x21, 0xbc, 0xc0, 0xff, 0x04, 0xd0, 0x7e, 0xf9, 0xaf, 0x3f, 0xd7, 0xe6,
	0xca, 0xa5, 0x46, 0x69, 0xe3, 0x8f, 0x26, 0xa9, 0x23, 0xfc, 0xfb, 0xaf, 0x2f, 0xa8, 0xf9, 0x9a,
	0x54, 0xaf, 0xbd, 0xa0, 0x3b, 0x72, 0xae, 0x3e, 0xd8, 0xa3, 0x20, 0x04, 0x1b, 0x2f, 0x9f, 0xb4,
	0xc3, 0xdc, 0xdb, 0x22, 0xf7, 0xf6, 0x5b, 0x3e, 0xe8, 0x7b, 0x36, 0xa6, 0x63, 0x5c, 0xcb, 0x1f,
	0xe6, 0x11, 0x59, 0xc2, 0x01, 0xa8, 0xf5, 0x60, 0x7d, 0x36, 0x37, 0x42, 0x15, 0x45, 0xa0, 0xe6,
	0x01, 0x31, 0x6e, 0x46, 0x9e, 0xed, 0x43, 0x0a, 0xb3, 0x3c, 0x85, 0xc7, 0x89, 0x00, 0xa7, 0x6c,
	0x4c, 0x88, 0x27, 0x37, 0xd1, 0xb3, 0x79, 0x48, 0xaa, 0x08, 0x4d, 0xad, 0x39, 0xce, 0x9f, 0x09,
	0x37, 0x24, 0x9c, 0xb3, 0x0f, 0x5d, 0x7f, 0xfb, 0x25, 0xb0, 0xcf, 0x6b, 0xd8, 0xdf, 0xb1, 0x31,
	0xc0, 0x3e, 0x8c, 0x9e, 0x19, 0x3b, 0x42, 0x53, 0x6b, 0x41, 0xc3, 0x8e, 0xe0, 0x86, 0x84, 0x0b,
	0xf6, 0xdd, 0x1d, 0x60, 0x5f, 0xd4, 0xb3, 0xef, 0xee, 0x48, 0x76, 0x78, 0x06, 0x76, 0x81, 0xa6,
	0x56, 0x59, 0xcf, 0x2e, 0xe0, 0x86, 0x84, 0xf3, 0xd5, 0x0f, 0x70, 0xf1, 0x15, 0xcd, 0xea, 0x5f,
	0xe2, 0xf4, 0x03, 0x54, 0xfe, 0x11, 0x59, 0x0a, 0x94, 0xfa, 0x89, 0x66, 0xf5, 0x71, 0x84, 0x6a,
	0x80, 0x67, 0x00, 0x72, 0x88, 0xa6, 0xc0, 0xc8, 0xc8, 0x21, 0x2a, 0x22, 0x40, 0x93, 0x00, 0x39,
	0xc8, 0x59, 0xa8, 0x66, 0xe4, 0x20, 0x22, 0x54, 0x03, 0x3c, 0x0f, 0x7b, 0x84, 0x74, 0x3d, 0x6f,
	0x04, 0x19, 0x2c, 0xf1, 0x0c, 0x5a, 0x09, 0xfc, 0xb1, 0xe7, 0x8d, 0x42, 0x74, 0xa5, 0x2b, 0x1e,
	0xcd, 0x57, 0xc4, 0x90, 0x50, 0x6a, 0xd5, 0x38, 0x77, 0x16, 0x96, 0x44, 0x58, 0x5e, 0x3b, 0xf5,
	0xa7, 0x43, 0xb7, 0x0f, 0xcc, 0x75, 0x4d, 0xed, 0xdf, 0xf1, 0x41, 0x50, 0x3b, 0x95, 0x3f, 0x58,
	0xed, 0x38, 0x00, 0xb5, 0x1a, 0x9a, 0xda, 0x71, 0x84, 0x2a, 0x8a, 0xc0, 0x77, 0x60, 0xf7, 0xce,
	0x77, 0x28, 0xa4, 0xd0, 0xd4, 0xec, 0xc0, 0x63, 0x36, 0x46, 0x54, 0x10, 0x3d, 0xb3, 0x1d, 0x88,
	0xd0, 0xd4, 0x32, 0x35, 0x3b, 0x10, 0xc1, 0x0d, 0x09, 0xa7, 0xe6, 0xe7, 0xc4, 0xe0, 0xa2, 0x0c,
	0xec, 0xcb, 0x9c, 0xfd, 0x51, 0x02, 0x7e, 0xc2, 0xc6, 0x74, 0x08, 0x1f, 0x1a, 0x12, 0xef, 0x91,
	0x2a, 0x02, 0x52, 0x6b, 0x85, 0x13, 0xeb, 0x90, 0x86, 0x44, 0x52, 0xf3, 0x2b, 0x52, 0x8f, 0xb4,
	0x1a, 0x78, 0x1f, 0x6a, 0x96, 0xfc, 0x42, 0x8c, 0xeb, 0xd4, 0x22, 0x48, 0xc8, 0x7f, 0x42, 0x1a,
	0xb1, 0x20, 0xd4, 0x7a, 0xa4, 0x59, 0x7c, 0x19, 0xa5, 0xae, 0x46, 0xa1, 0xe6, 0x1b, 0x52, 0x13,
	0xa6, 0x05, 0xa9, 0xac, 0xf2, 0x54, 0xd6, 0x92, 0xfa, 0x09, 0xc3, 0x3a, 0x4b, 0x02, 0x10, 0x26,
	0x72, 0x4c, 0xea, 0x6a, 0x04, 0x6a, 0x59, 0x3c, 0x8f, 0x8c, 0x10, 0x35, 0x25, 0x04, 0x35, 0xdf,
	0x92, 0x86, 0x74, 0x3f, 0xc8, 0x63, 0x4d, 0x33, 0x25, 0xa7, 0x6c, 0xe0, 0xb9, 0x4d, 0x6f, 0x3b,
	0xb5, 0x1b, 0xf1, 0x18, 0x66, 0x72, 0x4a, 0x9a, 0xf1, 0x28, 0xd4, 0x6a, 0x69, 0xe6, 0x44, 0x86,
	0xa9, 0xab, 0x61, 0xf8, 0x9e, 0xe0, 0x60, 0x48, 0xe4, 0xb1, 0x66, 0x4f, 0xc0, 0x66, 0xe4, 0x83,
	0xa2, 0x3d, 0x81, 0x80, 0xd4, 0x7a, 0xa2, 0xd9, 0x13, 0xb0, 0x0f, 0x25, 0x92, 0xcf, 0xc0, 0x68,
	0x48, 0xc1, 0x44, 0x80, 0xf8, 0x3f, 0x9a, 0x19, 0xf8, 0x66, 0x48, 0xc1, 0x48, 0x6a, 0x23, 0xf1,
	0x18, 0xcd, 0x40, 0x3c, 0x0a, 0xb5, 0x9e, 0x6a, 0x66, 0x40, 0x86, 0xa9, 0xab, 0x61, 0xa8, 0xb9,
	0xcf, 0x75, 0x21, 0xe8, 0x09, 0x4b, 0x7c, 0xc6, 0x33, 0x59, 0x4d, 0x7b, 0xab, 0x83, 0x9e, 0xcf,
	0x25, 0x21, 0xe8, 0x81, 0x1f, 0x1e, 0x70, 0x49, 0x88, 0xb0, 0xd4, 0x5a, 0xe7, 0xfc, 0x5a, 0x70,
	0x15, 0x81, 0xa9, 0xf9, 0x82, 0x54, 0x6c, 0x57, 0xbc, 0x8d, 0xff, 0xe5, 0xb4, 0x2b, 0x09, 0xe4,
	0x91, 0x7b, 0xd7, 0x29, 0xdb, 0x2e, 0xbc, 0x89, 0xdb, 0x84, 0x44, 0x10, 0x6a, 0x6d, 0x70, 0xb6,
	0x74, 0x4c, 0x45, 0x60, 0xe8, 0xc6, 0xdf, 0x65, 0xe5, 0xf4, 0xf3, 0xad, 0xeb, 0x78, 0x37, 0xfc,
	0x40, 0x72, 0x74, 0xff, 0x03, 0xc9, 0x59, 0x49, 0x3d, 0x92, 0x1c, 0xaa, 0xe7, 0x89, 0x07, 0xb9,
	0xe7, 0x89, 0xb3, 0x52, 0xec, 0x44, 0xa1, 0x9c, 0x08, 0x66, 0x73, 0x4f, 0x04, 0x0c, 0xaf, 0x9c,
	0x09, 0x14, 0x4f, 0x9f, 0xcb, 0xf5, 0x74, 0xc0, 0x4b, 0x43, 0x53, 0x5d, 0x79, 0x3e, 0xdf, 0x95,
	0xd9, 0x14, 0xa8, 0xbe, 0xac, 0x9a, 0xea, 0x42, 0xbe, 0xa9, 0x8a, 0x10, 0x22, 0x8b, 0x57, 0x8a,
	0x27, 0x2e, 0xe6, 0x79, 0xe2, 0x59, 0x09, 0xbb, 0xe2, 0x51, 0xcc, 0xd8, 0xca, 0xf9, 0xc6, 0xc6,
	0xf8, 0xb1, 0xb5, 0x1d, 0xaa, 0xbe, 0x54, 0xc9, 0xf5, 0x25, 0x36, 0x8b, 0xc8, 0x99, 0xf6, 0x54,
	0x67, 0x21, 0x59, 0xce, 0xc2, 0xa0, 0xc8, 0x5b, 0x4e, 0x92, 0x06, 0x61, 0xe4, 0x19, 0xc4, 0x59,
	0x29, 0x61, 0x11, 0xc7, 0x09, 0x6d, 0xaf, 0xe6, 0x68, 0xfb, 0x59, 0x29, 0xae, 0xee, 0xa7, 0x29,
	0xca, 0xbc, 0x94, 0xa7, 0xcc, 0x2c, 0x97, 0x98, 0x36, 0xef, 0xa9, 0x9a, 0x5a, 0xcb, 0xd2, 0x54,
	0x36, 0x1b, 0x1f, 0xb0, 0xa8, 0x25, 0xa5, 0xb1, 0x9e, 0x27, 0x8d, 0x2c, 0x85, 0x98, 0x38, 0x1e,
	0xc4, 0x44, 0xad, 0x91, 0x29, 0x6a, 0xb0, 0x1d, 0x22, 0x59, 0xdb, 0xc6, 0xc2, 0xd4, 0xd4, 0x0b,
	0xd3, 0x59, 0x49, 0x4a, 0xd3, 0xf1, 0x22, 0x99, 0xe7, 0x80, 0x8d, 0x7f, 0x5a, 0xc4, 0x54, 0x3f,
	0x7d, 0xce, 0xed, 0x09, 0x35, 0x07, 0xa4, 0x09, 0xdb, 0x14, 0x34, 0x67, 0x6c, 0x4f, 0xac, 0x19,
	0xae, 0x60, 0x07, 0xed, 0x94, 0xef, 0xd3, 0x76, 0x32, 0x06, 0x6c, 0xe1, 0x50, 0x8e, 0xce, 0xed,
	0xc9, 0x89, 0xeb, 0x4f, 0xef, 0x3a, 0x75, 0xaa, 0xb6, 0x9a, 0x0e, 0x69, 0x00, 0x53, 0x28, 0x4d,
	0x8c, 0x28, 0xfc, 0x52, 0x7a, 0x75, 0x3f, 0x22, 0xae, 0x5a, 0x11, 0x4f, 0x8d, 0x2a, 0x8d, 0x88,
	0x26, 0x14, 0x10, 0x46, 0x33, 0x5b, 0x84, 0x86, 0x4b, 0x4b, 0x9c, 0x46, 0x34, 0xaa, 0x34, 0xbb,
	0x3b, 0x9c, 0x66, 0xae, 0x20, 0xcd, 0xee, 0x4e, 0x0a, 0x0d, 0x6f, 0x44, 0xcb, 0x13, 0xc8, 0x72,
	0xe6, 0x8b, 0x2c, 0xcf, 0xe5, 0x50, 0xa9, 0x07, 0x96, 0x27, 0x6a, 0x8d, 0x31, 0x41, 0x45, 0x0b,
	0x45, 0x99, 0x50, 0x49, 0x88, 0x29, 0xac, 0xa9, 0x4b, 0xa0, 0xe9, 0x8a, 0xab, 0x2b, 0xe3, 0x59,
	0xe4, 0x3c, 0xfb, 0xf7, 0xe3, 0x61, 0xc2, 0x1b, 0xb1, 0xc0, 0x47, 0x00, 0xb4, 0xa1, 0x6a, 0xe0,
	0x3f, 0xc6, 0x52, 0x2e, 0x52, 0x4d, 0xf8, 0x6f, 0xbc, 0x9a, 0xa8, 0x15, 0x6d, 0x84, 0x50, 0xab,
	0x19, 0x51, 0xa5, 0xc8, 0x46, 0xe0, 0x32, 0x1e, 0xdf, 0x08, 0xa2, 0x11, 0xd1, 0x84, 0x92, 0xce,
	0x68, 0x48, 0x11, 0x1a, 0xae, 0xf6, 0x71, 0x1a, 0xd1, 0x68, 0xfe, 0x4e, 0x56, 0x80, 0x46, 0xca,
	0x3f, 0xa3, 0x32, 0x38, 0xd5, 0xeb, 0xfb, 0x51, 0x45, 0xce, 0x10, 0xd1, 0x99, 0x34, 0xd1, 0x61,
	0xba, 0x64, 0x59, 0x28, 0x90, 0xb0, 0x0a, 0xc6, 0x18, 0x7e, 0xc2, 0x1e, 0xde, 0x53, 0x83, 0x20,
	0x42, 0x44, 0x08, 0xbb, 0x00, 0xb5, 0x9b, 0x53, 0xf2, 0x50, 0xe8, 0x90, 0xb4, 0x15, 0xc6, 0xb8,
	0x54, 0xa4, 0xc6, 0xc8, 0x71, 0xe2, 0x35, 0xe2, 0x0e, 0xb4, 0x7a, 0xa1, 0x85, 0x30, 0xba, 0x5a,
	0x91, 0xd5, 0xe3, 0xa2, 0x1e, 0x5f, 0x3d, 0xd1, 0x88, 0x4a, 0x43, 0x76, 0xc5, 0xb8, 0xea, 0x45,
	0x4a, 0x8b, 0x9c, 0x2c, 0x5e, 0x1a, 0xee, 0x50, 0xdf, 0x34, 0x66, 0x6d, 0x8c, 0xaf, 0x51, 0xf0,
	0x4d, 0x0b, 0x7a, 0x7e, 0xca, 0x9b, 0x16, 0xb6, 0x9a, 0x57, 0x04, 0xea, 0xbd, 0x62, 0x36, 0xc8,
	0x68, 0x9a, 0x9c, 0x66, 0xef, 0x7e, 0x34, 0x47, 0xae, 0xdc, 0xfe, 0x70, 0x44, 0x0b, 0x9b, 0x5a,
	0xbf, 0x92, 0x95, 0x34, 0x2b, 0x33, 0x1b, 0x64, 0xf6, 0xd6, 0xb9, 0x83, 0x5b, 0x45, 0xf6, 0x68,
	0xbe, 0x04, 0x57, 0x85, 0x93, 0x75, 0xf6, 0x55, 0x5f, 0x38, 0x74, 0xff, 0xc1, 0x17, 0x33, 0xad,
	0x5f, 0xc8, 0x72, 0x8a, 0x87, 0xa5, 0x10, 0xbc, 0x50, 0x09, 0x32, 0xef, 0xf2, 0xd2, 0xe2, 0x2b,
	0xe6, 0x55, 0x24, 0x3e, 0xba, 0xac, 0xd2, 0xc4, 0x97, 0x12, 0x5f, 0x30, 0xbe, 0xb8, 0x88, 0x42,
	0xf1, 0xa3, 0x15, 0x50, 0xdd, 0xaa, 0xc8, 0x0a, 0x5c, 0xa6, 0x57, 0xa0, 0x30, 0x64, 0x96, 0xf0,
	0x49, 0x0c, 0x29, 0x35, 0xfc, 0x4c, 0xcc, 0xa4, 0x3f, 0xa5, 0xc4, 0x7f, 0xae, 0xc6, 0xcf, 0xba,
	0x30, 0x4b, 0xcb, 0x5f, 0xf5, 0xa5, 0x22, 0xf9, 0xe3, 0x0b, 0xb1, 0xb4, 0x35, 0x56, 0x0c, 0xa9,
	0xc8, 0x1a, 0xa3, 0x1b, 0x2f, 0x14, 0xff, 0x07, 0x11, 0x5f, 0x71, 0xa2, 0x94, 0xf8, 0x9f, 0xa9,
	0xf1, 0x75, 0x17, 0x5b, 0x28, 0xb4, 0x4d, 0x56, 0x35, 0xce, 0x53, 0x64, 0xfe, 0xe5, 0x9d, 0x15,
	0xa2, 0xb8, 0x22, 0x8f, 0xd2, 0xad, 0x26, 0x85, 0x61, 0x4b, 0x65, 0xc8, 0xb8, 0x8d, 0x4a, 0xab,
	0x21, 0xe1, 0x2c, 0x45, 0x6a, 0x90, 0x77, 0x4c, 0x69, 0x2b, 0xa0, 0xa8, 0x7b, 0x91, 0x15, 0x48,
	0x2c, 0x6e, 0x94, 0x7d, 0xc2, 0x3c, 0x8a, 0x64, 0x2f, 0xef, 0x87, 0x10, 0xc5, 0x4f, 0xe8, 0x0d,
	0x40, 0x7e, 0x91, 0x12, 0x7f, 0x53, 0x8d, 0xaf, 0xbd, 0xff, 0x41, 0xc1, 0x2f, 0x49, 0x33, 0xe1,
	0x12, 0x29, 0x91, 0xff, 0xaf, 0x46, 0x4e, 0xbf, 0xeb, 0x91, 0x61, 0x8f, 0xdf, 0xf0, 0xbf, 0x40,
	0xcd, 0x34, 0x66, 0x7e, 0xdc, 0xed, 0x0f, 0xfd, 0x41, 0xd0, 0x6d, 0xf7, 0xbc, 0xf1, 0xd6, 0xc5,
	0xc0, 0xb9, 0xe0, 0xb6, 0xf5, 0xce, 0xbd, 0x0e, 0x98, 0x13, 0x39, 0x34, 0xfc, 0x53, 0x59, 0x6f,
	0xb3, 0xef, 0xb8, 0x9b, 0x7d, 0x6f, 0x93, 0xd9, 0xd9, 0x16, 0xb3, 0xb3, 0xee, 0x02, 0xef, 0xd8,
	0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0x47, 0x96, 0x51, 0x92, 0x40, 0x1c, 0x00, 0x00,
}
