// Code generated by protoc-gen-go-json. DO NOT EDIT.
// versions:
// - protoc-gen-go-json v0.0.0-dev
// - protoc             v3.17.3
// source: gogo.proto

package test

import (
	golang "github.com/TheThingsIndustries/protoc-gen-go-json/golang"
	jsonplugin "github.com/TheThingsIndustries/protoc-gen-go-json/jsonplugin"
	types "github.com/TheThingsIndustries/protoc-gen-go-json/test/types"
)

// MarshalProtoJSON marshals the MessageWithGoGoOptions message to JSON.
func (x *MessageWithGoGoOptions) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.EuiWithCustomName) > 0 || s.HasField("eui_with_custom_name") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("eui_with_custom_name")
		s.WriteBytes(x.EuiWithCustomName)
	}
	if len(x.EuiWithCustomNameAndType) > 0 || s.HasField("eui_with_custom_name_and_type") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("eui_with_custom_name_and_type")
		types.MarshalHEX(s.WithField("eui_with_custom_name_and_type"), x.EuiWithCustomNameAndType)
	}
	if len(x.NonNullableEuiWithCustomNameAndType) > 0 || s.HasField("non_nullable_eui_with_custom_name_and_type") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("non_nullable_eui_with_custom_name_and_type")
		types.MarshalHEX(s.WithField("non_nullable_eui_with_custom_name_and_type"), x.NonNullableEuiWithCustomNameAndType)
	}
	if len(x.EuisWithCustomNameAndType) > 0 || s.HasField("euis_with_custom_name_and_type") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("euis_with_custom_name_and_type")
		types.MarshalHEXArray(s.WithField("euis_with_custom_name_and_type"), x.EuisWithCustomNameAndType)
	}
	if x.Duration != nil || s.HasField("duration") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("duration")
		if x.Duration == nil {
			s.WriteNil()
		} else {
			golang.MarshalDuration(s, x.Duration)
		}
	}
	if x.NonNullableDuration != nil || s.HasField("non_nullable_duration") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("non_nullable_duration")
		if x.NonNullableDuration == nil {
			s.WriteNil()
		} else {
			golang.MarshalDuration(s, x.NonNullableDuration)
		}
	}
	if x.Timestamp != nil || s.HasField("timestamp") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("timestamp")
		if x.Timestamp == nil {
			s.WriteNil()
		} else {
			golang.MarshalTimestamp(s, x.Timestamp)
		}
	}
	if x.NonNullableTimestamp != nil || s.HasField("non_nullable_timestamp") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("non_nullable_timestamp")
		if x.NonNullableTimestamp == nil {
			s.WriteNil()
		} else {
			golang.MarshalTimestamp(s, x.NonNullableTimestamp)
		}
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the MessageWithGoGoOptions to JSON.
func (x MessageWithGoGoOptions) MarshalJSON() ([]byte, error) {
	return jsonplugin.DefaultMarshalerConfig.Marshal(&x)
}

// UnmarshalProtoJSON unmarshals the MessageWithGoGoOptions message from JSON.
func (x *MessageWithGoGoOptions) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "eui_with_custom_name", "euiWithCustomName":
			s.AddField("eui_with_custom_name")
			x.EuiWithCustomName = s.ReadBytes()
		case "eui_with_custom_name_and_type", "euiWithCustomNameAndType":
			s.AddField("eui_with_custom_name_and_type")
			x.EuiWithCustomNameAndType = types.UnmarshalHEX(s.WithField("eui_with_custom_name_and_type", false))
		case "non_nullable_eui_with_custom_name_and_type", "nonNullableEuiWithCustomNameAndType":
			s.AddField("non_nullable_eui_with_custom_name_and_type")
			x.NonNullableEuiWithCustomNameAndType = types.UnmarshalHEX(s.WithField("non_nullable_eui_with_custom_name_and_type", false))
		case "euis_with_custom_name_and_type", "euisWithCustomNameAndType":
			s.AddField("euis_with_custom_name_and_type")
			if s.ReadNil() {
				x.EuisWithCustomNameAndType = nil
				return
			}
			x.EuisWithCustomNameAndType = types.UnmarshalHEXArray(s.WithField("euis_with_custom_name_and_type", false))
		case "duration":
			s.AddField("duration")
			if s.ReadNil() {
				x.Duration = nil
				return
			}
			v := golang.UnmarshalDuration(s)
			if s.Err() != nil {
				return
			}
			x.Duration = v
		case "non_nullable_duration", "nonNullableDuration":
			s.AddField("non_nullable_duration")
			if s.ReadNil() {
				x.NonNullableDuration = nil
				return
			}
			v := golang.UnmarshalDuration(s)
			if s.Err() != nil {
				return
			}
			x.NonNullableDuration = v
		case "timestamp":
			s.AddField("timestamp")
			if s.ReadNil() {
				x.Timestamp = nil
				return
			}
			v := golang.UnmarshalTimestamp(s)
			if s.Err() != nil {
				return
			}
			x.Timestamp = v
		case "non_nullable_timestamp", "nonNullableTimestamp":
			s.AddField("non_nullable_timestamp")
			if s.ReadNil() {
				x.NonNullableTimestamp = nil
				return
			}
			v := golang.UnmarshalTimestamp(s)
			if s.Err() != nil {
				return
			}
			x.NonNullableTimestamp = v
		}
	})
}

// UnmarshalJSON unmarshals the MessageWithGoGoOptions from JSON.
func (x *MessageWithGoGoOptions) UnmarshalJSON(b []byte) error {
	return jsonplugin.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the SubMessage message to JSON.
func (x *SubMessage) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Field != "" || s.HasField("field") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("field")
		s.WriteString(x.Field)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the SubMessage to JSON.
func (x SubMessage) MarshalJSON() ([]byte, error) {
	return jsonplugin.DefaultMarshalerConfig.Marshal(&x)
}

// UnmarshalProtoJSON unmarshals the SubMessage message from JSON.
func (x *SubMessage) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "field":
			s.AddField("field")
			x.Field = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the SubMessage from JSON.
func (x *SubMessage) UnmarshalJSON(b []byte) error {
	return jsonplugin.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the MessageWithNullable message to JSON.
func (x *MessageWithNullable) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Sub != nil || s.HasField("sub") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("sub")
		x.Sub.MarshalProtoJSON(s.WithField("sub"))
	}
	if len(x.Subs) > 0 || s.HasField("subs") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("subs")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Subs {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("subs"))
		}
		s.WriteArrayEnd()
	}
	if x.OtherSub != nil || s.HasField("other_sub") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("other_sub")
		// NOTE: SubMessageWithoutMarshalers does not seem to implement MarshalProtoJSON.
		golang.MarshalMessage(s, x.OtherSub)
	}
	if len(x.OtherSubs) > 0 || s.HasField("other_subs") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("other_subs")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.OtherSubs {
			s.WriteMoreIf(&wroteElement)
			// NOTE: SubMessageWithoutMarshalers does not seem to implement MarshalProtoJSON.
			golang.MarshalMessage(s, element)
		}
		s.WriteArrayEnd()
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the MessageWithNullable to JSON.
func (x MessageWithNullable) MarshalJSON() ([]byte, error) {
	return jsonplugin.DefaultMarshalerConfig.Marshal(&x)
}

// UnmarshalProtoJSON unmarshals the MessageWithNullable message from JSON.
func (x *MessageWithNullable) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "sub":
			if s.ReadNil() {
				x.Sub = nil
				return
			}
			x.Sub = &SubMessage{}
			x.Sub.UnmarshalProtoJSON(s.WithField("sub", true))
		case "subs":
			s.AddField("subs")
			if s.ReadNil() {
				x.Subs = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.Subs = append(x.Subs, nil)
					return
				}
				v := &SubMessage{}
				v.UnmarshalProtoJSON(s.WithField("subs", false))
				if s.Err() != nil {
					return
				}
				x.Subs = append(x.Subs, v)
			})
		case "other_sub", "otherSub":
			s.AddField("other_sub")
			if s.ReadNil() {
				x.OtherSub = nil
				return
			}
			// NOTE: SubMessageWithoutMarshalers does not seem to implement UnmarshalProtoJSON.
			var v SubMessageWithoutMarshalers
			golang.UnmarshalMessage(s, &v)
			x.OtherSub = &v
		case "other_subs", "otherSubs":
			s.AddField("other_subs")
			if s.ReadNil() {
				x.OtherSubs = nil
				return
			}
			s.ReadArray(func() {
				// NOTE: SubMessageWithoutMarshalers does not seem to implement UnmarshalProtoJSON.
				var v SubMessageWithoutMarshalers
				golang.UnmarshalMessage(s, &v)
				x.OtherSubs = append(x.OtherSubs, &v)
			})
		}
	})
}

// UnmarshalJSON unmarshals the MessageWithNullable from JSON.
func (x *MessageWithNullable) UnmarshalJSON(b []byte) error {
	return jsonplugin.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the MessageWithEmbedded message to JSON.
func (x *MessageWithEmbedded) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Sub != nil || s.HasField("sub") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("sub")
		x.Sub.MarshalProtoJSON(s.WithField("sub"))
	}
	if x.OtherSub != nil || s.HasField("other_sub") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("other_sub")
		// NOTE: SubMessageWithoutMarshalers does not seem to implement MarshalProtoJSON.
		golang.MarshalMessage(s, x.OtherSub)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the MessageWithEmbedded to JSON.
func (x MessageWithEmbedded) MarshalJSON() ([]byte, error) {
	return jsonplugin.DefaultMarshalerConfig.Marshal(&x)
}

// UnmarshalProtoJSON unmarshals the MessageWithEmbedded message from JSON.
func (x *MessageWithEmbedded) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "sub":
			if s.ReadNil() {
				x.Sub = nil
				return
			}
			x.Sub = &SubMessage{}
			x.Sub.UnmarshalProtoJSON(s.WithField("sub", true))
		case "other_sub", "otherSub":
			s.AddField("other_sub")
			if s.ReadNil() {
				x.OtherSub = nil
				return
			}
			// NOTE: SubMessageWithoutMarshalers does not seem to implement UnmarshalProtoJSON.
			var v SubMessageWithoutMarshalers
			golang.UnmarshalMessage(s, &v)
			x.OtherSub = &v
		}
	})
}

// UnmarshalJSON unmarshals the MessageWithEmbedded from JSON.
func (x *MessageWithEmbedded) UnmarshalJSON(b []byte) error {
	return jsonplugin.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the MessageWithNullableEmbedded message to JSON.
func (x *MessageWithNullableEmbedded) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Sub != nil || s.HasField("sub") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("sub")
		x.Sub.MarshalProtoJSON(s.WithField("sub"))
	}
	if x.OtherSub != nil || s.HasField("other_sub") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("other_sub")
		// NOTE: SubMessageWithoutMarshalers does not seem to implement MarshalProtoJSON.
		golang.MarshalMessage(s, x.OtherSub)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the MessageWithNullableEmbedded to JSON.
func (x MessageWithNullableEmbedded) MarshalJSON() ([]byte, error) {
	return jsonplugin.DefaultMarshalerConfig.Marshal(&x)
}

// UnmarshalProtoJSON unmarshals the MessageWithNullableEmbedded message from JSON.
func (x *MessageWithNullableEmbedded) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "sub":
			if s.ReadNil() {
				x.Sub = nil
				return
			}
			x.Sub = &SubMessage{}
			x.Sub.UnmarshalProtoJSON(s.WithField("sub", true))
		case "other_sub", "otherSub":
			s.AddField("other_sub")
			if s.ReadNil() {
				x.OtherSub = nil
				return
			}
			// NOTE: SubMessageWithoutMarshalers does not seem to implement UnmarshalProtoJSON.
			var v SubMessageWithoutMarshalers
			golang.UnmarshalMessage(s, &v)
			x.OtherSub = &v
		}
	})
}

// UnmarshalJSON unmarshals the MessageWithNullableEmbedded from JSON.
func (x *MessageWithNullableEmbedded) UnmarshalJSON(b []byte) error {
	return jsonplugin.DefaultUnmarshalerConfig.Unmarshal(b, x)
}
