name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

# Builds images for target boards.
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.25']
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go }}

      - name: Install protoc
        run: |
          PROTOC_VERSION=34.1
          archive="$RUNNER_TEMP/protoc.zip"
          url="https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip"
          curl -sSLo "$archive" "$url"
          unzip -q "$archive" -d "$HOME/.local"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Cache tools
        uses: actions/cache@v6
        with:
          path: |
            ./hack/bin
          key: ${{ runner.os }}-aptre-tools-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-aptre-tools-

      - name: Test Go
        run: make test

      - name: Lint Go
        run: make lint

      - name: Check generated output
        run: make check-gengo
